### ISSUE TITLE
Organisers section

### ISSUE THREAD

**Issue by chucheria** [rladies/rladies-website#3]
## Organisers section

Include an organisers section where organisers can find materials for their chapters.

### Could have
- Starter kit
- How to add the meetup R-Ladies Tag
- Branding stuff: stickers, roll up and so on.
- If there's any meetup space available.
- Who to talk to in case of any doubt.

**Comment by gdequeiroz** [comment]
Hi @chucheria, this a great idea but I think this should go to the wiki [here](https://github.com/rladies/starter-kit/wiki). The website should only contain info for the general audience IMO.

**Comment by chucheria** [comment]
@gdequeiroz much better! I'll close the issue then.
